### ISSUE TITLE
Navigation über 'Pagination' nicht möglich

### ISSUE THREAD

**Issue by alfredbez** [lunow/lunow.github.io#1]
Wenn man auf eine Seite über die Pagination unten auf der Seite wechselt, sind die Links in der Pagination kaputt.

Beispiel: Man befindet sich auf http://www.interaktionsdesigner.de/page/2/, der Link zu Seite 3 ist jetzt http://www.interaktionsdesigner.de/page/2/page/3

**Comment by lunow** [comment]
Allerdings! Vielen Dank für den Hinweis. Ich schaue mir das an...
